name: Generate ASCII Artwork
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4  #to read code from repo

        - name: List Repo Files
          run: ls -ltra

        - name: Executing Shell Script
          run: |
            chmod +x .github/workflows/ascii-script.sh
            ./.github/workflows/ascii-script.sh
